### ISSUE TITLE
task - api utils (integración)

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#113]
## description 
integración en forma de llamadas a la API Rest del backend

## to-do
- [x] intalar axios
- [x] configurar axios
- [x] solicitar/proveer documentación sobre los endpoints
- [x] CRUD events
- [x] CRUD participation
- [x] CRUD infraestructure
- [x] CRUD sponsorship

## accept
- [ ] el frontend dispone de una configuración consistente de axios
- [ ] existen funciones para realizar peticiones a la API básicas
