### ISSUE TITLE
task - automatizar despliegue

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#115]
## description 
queremos automatizar el despliegue de la aplicación, según los requisitos, el despliegue debe ser dual, entorno de **"stage"**
donde los usuarios piloto probarán la aplicación y entorno de **"production"** donde se mantiene la última versión funcional estable de la aplicación

## to-do
- [x] obtener credenciales de servidores para realizar el despliegue
- [x] automatizar el despliegue
    - [x] a stage cuando se crea una PR a main
    - [x] a prod cuando se mergea una PR a main 

## accept
- [ ] el despliegue queda totalmente automatizado
