### ISSUE TITLE
doc - UML

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#116]
## descripcion
descripción detallada de lo que debe ser documentado, como y donde.

## to-do
- [ ] completar el UML con las clases y atributos faltantes
- [ ] tipos y restricciones de los atributos 
- [ ] subir el uml (draw.io) a drive y garantizar que todos tienen acceso
