### ISSUE TITLE
backend - Swagger

### ISSUE THREAD

**Issue by pedalopon** [ISPP-Eventia/eventus#139]
## description 
Implement swagger for better endpoint documentation.

## to-do
- [ ] Install pom dependecies
- [ ] Add any necesary configuration to spring project

## accept
- [ ] Test swagger is working and available
