### ISSUE TITLE
backend - Testing

### ISSUE THREAD

**Issue by pedalopon** [ISPP-Eventia/eventus#140]
## description 
Develop new tests for controllers and refactor/complete services tests

## to-do
- [ ] Create a test for every Controller
- [ ] Refactor service test alredy done 
- [ ] Create new tests for services that hasn't been tested yet

## accept
A clear and concise description of the acceptance conditions
- [ ] All test pass
