### ISSUE TITLE
backend - Refactor classes

### ISSUE THREAD

**Issue by pedalopon** [ISPP-Eventia/eventus#141]
## description 
Refactor all clases that has been change in new uml version.
![unknown](https://user-images.githubusercontent.com/61872564/159137065-f7d8580c-079b-443e-8271-ded78cee19e1.png)

## to-do
- [ ] Refactor classes names
- [ ] Refactor attributes names
- [ ] Add new attributes
- [ ] Any other changes neededed
