### ISSUE TITLE
task - session endpoints

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#144]
## description 
We need login, logout and sign up endpoints 

## to-do
- [ ] login endpoint (session based) 
- [ ] sing up endpoint (receives user body)
- [ ] logout endpoint (session based, empty request)

## accept
- [ ] the backend provides basic session endpoints
