### ISSUE TITLE
task - login form

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#145]
## description 
We need a simple login form in order to authenticate a user

## to-do
- [x] create a login and signup pages
- [x] create a loginForm and signupForm components
- [x] handle redirections (to login, after login ...)
- [x] handle localStorage user id saving

## accept
- [x] there is a login form component and a login page 
- [x] the user is correctly redirected to the login page and after login in
