### ISSUE TITLE
task - profile, profile info tab

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#146]
## description 
On the profile page, we need a tab with the basic profile info

## to-do
- [x] implement or take the profile page as starting point
- [x] implement or take the profile page tabs as second point
- [x] implement the profile info tab

## accept
- [x] on the profile page there is a tab with the profile info
