### ISSUE TITLE
task - profile, tickets

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#148]
## description 
On the profile page, we need a tab with a list of owned tickets

## to-do
- [x] implement or take the profile page as starting point
- [x] implement or take the profile page tabs as second point
- [x] implement the tickets tab list

## accept
- [ ] on the profile page there is a tab with the owned tickets as a list
