### ISSUE TITLE
task - profile, locations

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#149]
## description 
On the profile page, we need a tab with a list of owned locations (infrastructures)

## to-do
- [x] implement or take the profile page as starting point
- [x] implement or take the profile page tabs as second point
- [x] implement the owned locations tab list

## accept
- [x] on the profile page there is a tab with the owned locations as a list
