### ISSUE TITLE
task - user and logout links

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#150]
## description 
On the right side of the header, we need a profile icon (redirects to profile tabs page) and a logout icon button that logs out the user (and redirects to the landing page or login page) 

## to-do
- [x] add the icon buttons
- [x] implement redirections

## accept
- [ ] the user has a direct link to the profile page
- [ ] the user can logout easily
