### ISSUE TITLE
task - profile info endpoint

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#151]
## description 
We need endpoints that provide user-related info

> note: all of them should be session-based, using the logged-in user in order to get and filter the data

## to-do
- [x] my events endpoint
- [x] my tickets endpoint
- [x] my locations endpoint
- [x] my profile endpoint

## accept
- [x] the backend provides endpoints in order to get logged in user info and related entities
