### ISSUE TITLE
task - payment form

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#153]
## description 
We need payment information / accounts / integrations

> note: the form might be included inside of other forms or maybe its response is needed before other form is submited

## to-do
- [ ] wait for the backend payment definition
- [ ] implement form / inputs for the required payment info

## accept
- [ ] the user has a friendly way of payment
