### ISSUE TITLE
task - payment endpoint

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#154]
## description 
we need a payment endpoint that receives the payment info from the user and executes it

> note: the payment handling consists of performing the payment from user to user and applying the app fees (check the fee definitions)

## to-do
- [ ] check possible implementations, especially existing libraries (Paypal?)
- [ ] implement an endpoint that receives the payment info and handles the payment

## accept
- [ ] the backend provides an endpoint to do payments
