### ISSUE TITLE
task - payments, integrate existing forms

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#155]
## related
- blocked by #153 

## description 
Once we have a payment form ready, we need to integrate it with the other forms that are implemented already

> note: participate, sponsor, request hosting ... 

## to-do
- [ ] participate form integration
- [ ] sponsor form integration
- [ ] hosting request form integration

## accept
- [ ] all the "paid" transaction forms are integrated with the payment form
