### ISSUE TITLE
devops - Implementar pruebas para el modelo Coordinates

### ISSUE THREAD

**Issue by carvilgar1** [ISPP-Eventia/eventus#185]
## descripcion
Incluir casos de prueba para el modelo Coordinates. 

## to-do
- [ ] Implementar pruebas de software para los atributos latitude y longitude siguiendo la estrategia de los valores extremos.
- [ ] Se deben contemplar casos de pruebas positivos y negativos.

## success criteria
- [ ] Se alcanza al menos un 60% de cobertura o mayor. Los casos de pruebas cubren los escenarios ilegales y legales
