### ISSUE TITLE
task - delete / edit, locations and events

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#187]
## description 
Necesitamos implementar UI para la funcionalidad de eliminación y edicion de eventos / locations

## to-do
- [x] tener en cuenta el id de usuario registrado para mostrar las funcionalidades como enabled
- [x] añadir el botón de eliminación
- [x] asegurar que los formularios pueden reusarse para la edición
- [x] mostrar el botón de editar  

## accept
- [x] un usuario puede editar y/o eliminar eventos y locations

**Comment by JSnow11** [comment]
## progress
The edit buttons have been added, they will redirect you to `events/< id >/edit` and the same for locations

We still need to implement the form initialization (with event / location data) and the update calls

**Comment by ferrabled** [comment]
Edit and delete working properly
