### ISSUE TITLE
task - visual improvements

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#188]
## description 
Mejoras visuales del frontend

## to-do
- [x] responsive
- [x] aceptación de patrocinios / eventos
- [x] tarjetas de usuario
- [x] typografias

## accept
- [x] mejor presentación visual del frontend par el usuario
