### ISSUE TITLE
task - check security issues

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#191]
## description 
Github dependabot detecta errores de seguridad segun dependencias, se debe comprobar y proponer una solución

## to-do
- [x] check de la [información de seguridad](https://github.com/ISPP-Eventia/eventus/security) 
- [x] proponer soluciones y comunicarlas
- [x] implementar soluciones si es posible

## accept
- [ ] problemas de seguridad resueltos
