### ISSUE TITLE
doc - review guide

### ISSUE THREAD

**Issue by GuilleX7** [ISPP-Eventia/eventus#193]
## descripcion
guía de revisión de la funcionalidad implementada en el sprint

## to-do
- [ ] análisis de la guia solicitada
- [ ] explicar la funcionalidad implementada
- [ ] pasos para revisar
- [ ] credenciales

## recursos
- guia: subida en la enseñanza virtual como un pdf con los elementos que debe contener la review guide
