### ISSUE TITLE
doc - competitors analysis 

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#20]
## descripcion
aplicar feedback y expandir el análisis de competencia según lo solicitado

## to-do
- [X] buscar más competidores 
- [X] especificar tipos o ámbitos de competencia
- [x] **TABLA COMPARATIVA**
     - [x] comparativa de funcionalidad 
     - [x] comparativa de precios
     - [x] comparativa de usabilidad, ui/ux
     - [x] comparativa de relevancia
     - [x] opiniones y debilidades de competidores
- [x] evidenciar los motivos de competencia
- [X] documentar el proceso de búsqueda

## recursos
- [feedback]()

**Comment by JSnow11** [comment]
## feedback
poner especial enfasis en la tabla comparativa
