### ISSUE TITLE
doc - cost analysis

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#21]
## descripcion
aplicar feedback y expandir el análisis de costos según lo solicitado

## to-do
- [x] concretar más costes
- [x] costes periódicos
- [x] costes de infraestructura
- [x] costes totales previstos
- [x] posibles costes futuros
- [ ] pco
- [x] justificaciones
- [x] análisis y predicciones de beneficios
- [x] ejemplos de opciones reales (servidor, dominio ...)

## recursos
- [feedback]()
