### ISSUE TITLE
doc - stack tecnológico 

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#22]
## descripcion
decidir y documentar el stack tecnológico a usar y justificarlo

## to-do
- [ ] análisis de habilidades
- [ ] análisis de objetivos
- [ ] análisis de innovación
- [x] propuesta de stack
- [x] decisión y justificación
- [ ] documentación de la arquitectura

## recursos
- [feedback]()

**Comment by carvilgar1** [comment]
Decisión y justificación en las notas de la diapositiva
