### ISSUE TITLE
devops - Implementar pruebas para el modelo User

### ISSUE THREAD

**Issue by carvilgar1** [ISPP-Eventia/eventus#220]
## descripcion
Incluir casos de prueba para el modelo User. 

## to-do
- [x] Implementar pruebas de software para cada atributo siguiendo la estrategia de los valores extremos.
- [x] Se deben contemplar casos de pruebas positivos y negativos.

## success criteria
- [x] Se alcanza al menos un 60% de cobertura o mayor. Los casos de pruebas cubren los escenarios ilegales y legales
