### ISSUE TITLE
devops - pruebas unitarias para el modelo Location

### ISSUE THREAD

**Issue by carvilgar1** [ISPP-Eventia/eventus#222]
## descripcion
Incluir casos de prueba para el modelo Location. 

## to-do
- [ ] Implementar pruebas de software para cada atributo siguiendo la estrategia de los valores extremos.
- [ ] Se deben contemplar casos de pruebas positivos y negativos.

## success criteria
- [ ] Se alcanza al menos un 60% de cobertura o mayor. Los casos de pruebas cubren los escenarios ilegales y legales
