### ISSUE TITLE
devops - pruebas unitarias para el modelo Participation

### ISSUE THREAD

**Issue by carvilgar1** [ISPP-Eventia/eventus#223]
## descripcion
Incluir casos de prueba para el modelo Participation. 

## to-do
- [x] Implementar pruebas de software para cada atributo siguiendo la estrategia de los valores extremos.
- [x] Se deben contemplar casos de pruebas positivos y negativos.

## success criteria
- [ ] Se alcanza al menos un 60% de cobertura o mayor. Los casos de pruebas cubren los escenarios ilegales y legales
