### ISSUE TITLE
backend - Admin role and role validations

### ISSUE THREAD

**Issue by pedalopon** [ISPP-Eventia/eventus#229]
## description 
Implement admin role and admin validation login for controller endpoints

## to-do
- [ ] Admin role
- [ ] Endpoint validation for admins
- [ ] Extras endpoints necesary to implement admin view

## accept
- [ ] Exits a admin role
- [ ] Admin user can do any request
- [ ] Normal user cant do admin actions
