### ISSUE TITLE
backend - populate initial dataset

### ISSUE THREAD

**Issue by pedalopon** [ISPP-Eventia/eventus#230]
## description 
Implement a realistic dateset for database population

## to-do
- [x] Update data.sql file with real data
- [x] Remove data not realistic from data.sql

## accept
A clear and concise description of the acceptance conditions
- [x] data.sql has been update with realistic data
- [x] Deployed application shows the new initial data
