### ISSUE TITLE
task - admin Ui adjustments

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#233]
## description 
Añadir, isAdmin, como condición para mostrar la vista de "dueño" de evento y ubicación.

se deben mostrar los botones de editar/eliminar, en vez de participar e sponsorizar

## to-do
- [x] esperar a la implementación en el backend
- [x] añadir la condición en eventDetails
- [x] añadir la condición en locationDetails

## accept
- [ ] un usuario admin es "dueño" de todos los eventos y ubicaciones
