### ISSUE TITLE
task - segmentar la event list

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#245]
## description 
Los usuarios pilotos encuentran la pagina de lista de eventos poco relevante, con un ordenado por creación poco útil,

Se propone:
- categorías para los eventos, mostrando los eventos divididos según la categoría
- añadir "premio" a los eventos y mostrar los eventos con premio a parte, ordenados por cantidad de premio
- eventos por "relevancia", teniendo en cuenta patrocinadores, participantes y dinero

## to-do
- [x] crear campo categoría en evento
- [x] endpoint para solicitar todas las categorías que existen
- [x] crear campo premio en evento y controlar el campo en las CRUD de evento
- [x] añadir el premio en el formulario 
- [x] calculo de la relevancia segun la fórmula: 

```
nºparticipantes * 0.3 + 
nºpatrocinadores * 0.3 + 
dineroRecolectado (patrocinios + participaciones) * 0.3
```

## accept
- [x] pagina de eventos más característica y relevante para el usuario
