### ISSUE TITLE
task - ordenar anuncios por cantidad ofrecida

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#246]
## description 
Ordenar los anuncios de un evento según la cantidad ofrecida e informar de dicha lógica en el formulario de patrocinio

## to-do
- [x] ordernar los anuncios
- [x] añadir el mensaje al formulario

## accept
- [x] los anuncios se ordenan por cantidad ofrecida
