### ISSUE TITLE
doc - differentiation and innovation 

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#25]
## descripcion
aclarar la diferenciación e innovación que ofrecemos

## to-do
- [x] diferenciación por unión de mercado
- [x] diferenciación por conexión de interesados
- [x] diferenciación por generalidad de uso
- [x] diferenciación por torneos/competiciones
- [x] diferenciación por usabilidad
- [x] innovación tecnológica
- [x] innovación funcional

## recursos
- slides
- doc
