### ISSUE TITLE
doc - slides design feedback

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#26]
## descripcion
mejorar la presentación visual e infográficamente

## to-do
- [X] más metáforas visuales
- [ ] nuevas diapositivas con esquema de colores de la app
- [ ] menos texto
- [ ] menos tablas, 1 slide x cada elemento
- [x] evitar texto pequeño
- [x] evitar mal contraste
- [x] evitar texto cercano a bordes
- [ ] unificar lenguaje
- [ ] formato y branding (caracterizar el diseño)
- [ ] preparación de la presentación

## recursos
![image](https://user-images.githubusercontent.com/47798577/155752600-af64a3e3-0cc2-4f42-9bea-d9ed3425b17e.png)

**Comment by JSnow11** [comment]
## Follow up
