### ISSUE TITLE
devops - Implementar pruebas unitarias para ParticipationService

### ISSUE THREAD

**Issue by carvilgar1** [ISPP-Eventia/eventus#269]
## descripcion
Incluir casos de prueba para el servicio Participation. 

## to-do
- [x] Implementar pruebas de software para cada método.
- [x] Se deben contemplar casos de pruebas positivos y negativos.

## success criteria
- [x] Se alcanza al menos un 60% de cobertura o mayor. Los casos de pruebas cubren los escenarios ilegales y legales
