### ISSUE TITLE
doc - pilot users extension

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#27]
## descripcion
definir el proceso y gestión del plan de usuarios piloto 

## to-do
- [x] encuesta
- [x] definir y concretar perfiles y tipos
- [x] relevancia de cada perfil (justificación)
- [x] plan de instrucciones/manuales
- [x] métodos de feedback (issue templates)

## recursos
- slides
- doc de usuarios piloto

**Comment by josaloroc** [comment]
Se han desarrollado los puntos del _to-do_ de la siguiente forma:

1. Para _encuesta_ se ha desarrollado un formulario de google para reunir información inicial para la siguiente semana respecto a nuestros usuarios piloto y/o público general.
2. Para _definir y concretar perfiles y tipo_ se ha establecido y explicado de forma general en una diapositiva (nº15) los roles.
3. Para _relevancia de cada perfil (justificación)_ se ha establecido como varios casos de perfiles con dicho rol y cómo usarían nuestra aplicación.
4. Para _plan de instrucciones/manuales_ hemos mencionado en una diapositiva el planteamiento y desarrollo de manuales de usuario conforme se vayan implementando las funcionalidades de la aplicación.
5. Como _métodos de feedback (issue templates)_ caben destacar varios elementos:
- Se usará uno de los templates de GitHub de issues para añadir la nueva funcionalidad referente a posible feedback recibido. Sugerencia: podemos marcar esa issue con una etiqueta de "feedback" para diferenciarla de las issues de funcionalidad que nosotros hemos definido para el proyecto.
- Hemos creado un formulario de incidencias disponible en todo momento para los usuarios piloto: el propósito de este formulario es informar de posibles errores o enviar sugerencias de inmediato.
- Planteamos para el futuro en las próximas semanas la creación de un nuevo formulario de carácter más general para recibir feedback en ciertos partes específicas del desarrollo, donde preguntaremos por opinión subjetiva del usuario. Se ha mencionado la intención de crear esto en las propias diapositivas.
