### ISSUE TITLE
devops - Implementar pruebas unitarias para ISponsorshipService

### ISSUE THREAD

**Issue by carvilgar1** [ISPP-Eventia/eventus#271]
## descripcion
Incluir casos de prueba para el servicio Sponsorship. 

## to-do
- [ ] Implementar pruebas de software para cada método.
- [ ] Se deben contemplar casos de pruebas positivos y negativos.

## success criteria
- [ ] Se alcanza al menos un 60% de cobertura o mayor. Los casos de pruebas cubren los escenarios ilegales y legales
