### ISSUE TITLE
devops - Implementar pruebas de integración para HostingController.java.

### ISSUE THREAD

**Issue by carvilgar1** [ISPP-Eventia/eventus#273]
## descripcion
Incluir casos de prueba para el controlador HostingController.java. 

## to-do
- [ ] Implementar pruebas de software para cada endpoint.
- [ ] Se deben contemplar casos de pruebas positivos y negativos.

## success criteria
- [ ] Se alcanza al menos un 60 por cien de cobertura o mayor. 
- [ ] Los casos de pruebas cubren los escenarios ilegales y legales
