### ISSUE TITLE
doc - testing plan

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#28]
## descripcion
se debe elaborar un plan de testeo a seguir 

## to-do
- [x] Definir el flujo de trabajo
- [x] Definir plantillas de commits
- [x] Definir estándares de calidad de la organización
- [x] Definir ciclo de integración continua

## recursos
- enlaces de documentos o archivos
- enlaces de recursos útiles
