### ISSUE TITLE
task - hashtags 

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#287]
## description 
necesitamos una función (utils) para generar un hashtag automatico en base a un evento

> se puede usar título y algún otro parametro

## to-do
- [x] definir la función
- [x] hacer uso de la función e incluir el hashtag en la detail page
- [x] incluirlo en las plantilles de post

## accept
- [x] podemos gener un hashtag para un evento
