### ISSUE TITLE
task - image inputs

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#288]
## description 
necesitamos un input de imagen (ant d) y un post procesado en el frontend para asegurar que los archivos son enviados en el formato correcto al backend

## to-do
- [ ] elegir componente
- [ ] post procesado , integración
- [ ] añadir a : sponsor, event, location ... forms

## accept
- [ ] Ul y procesado de imagenes funcional
