### ISSUE TITLE
task - image slider component

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#289]
## description 
puesto que eventos y locations pueden tener varias imagenes, necesitamos un slider de imagenes

> buscar componente en mui o antd

### context
> se verá la primera imagen y alguna forma de navegación adelante y atrás para ver otras imagenes

## to-do
- [ ] elegir componente
- [ ] definir molecule que use dicho componente
- [ ] hacer uso en event y location details

## accept
- [ ] image sliders en las paginas de detalle
