### ISSUE TITLE
task - recommend endpoint

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#290]
## description 
nuevo atributo de recomendación para eventos en función de eventos visitados y participaciones

### context
> se debe trackear que eventos se visitan y consultar las participaciones, comparar dichos eventos con eventos disponibles y calcular una métrica

## to-do
- [x] definir formula
- [x] trackear visitas en el endpoint de evento por id
- [x] celulo del atributo

## accept
- [x] los eventos tienen un atributo derivado que indica la recomendacion de dicho evento al usuario logueado
- [x] sistema de recomendacion funcionando
