### ISSUE TITLE
task - image upload and handling

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#291]
## description 
se debe poder subir imagenes y definir la estructura con le que se devolverán al consultarlas

> el frontend ya sigue un formato de json esperado, puede consutarse en `types/index`

## to-do
- [ ] entidad: Media
- [ ] añadir a entidades: event, sponsor, location
- [ ] procesar en endpoints de creación
- [ ] definir json de entrada y salida 

## accept

- [ ] servicios de subida/bajada de media funcionales
