### ISSUE TITLE
task - event tags

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#292]
## description 
necesitamos que los eventos se puedan etiquetar

> sería interesante implementar un selector que tenga valores ya existentes y la posibilidad de crear nuevos

### context
solicitado por usuarios piloto

## to-do
- [ ] añadir atributo de tags (set)
- [ ] implementar selector
- [ ] añadir filtro en event List (agrupar por etiquete)
- [ ] añadir a full text search

## accept
- [ ] eventos etiquetados
