### ISSUE TITLE
task - gpdr, términos y condiciones

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#318]
## description 
necesitamos proveer al usuario con los términos y condiciones definidos por el  dpo

## to-do

- [x] casilla de confirmación en el registro
- [x] link a los términos y condiciones
- [x] página o PDF con dichos términos 

## accept
- [x] un usuario puede ver los términos y condiciones de la app
- [ ] el usuario debe aceptarlos para poder registrarse

**Comment by JSnow11** [comment]
@GuilleX7 , se deben proporcionar los términos y condiciones cuando estos estén definidos.
