### ISSUE TITLE
doc - esquema y guión de presentación

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#32]
## descripcion
mejorar la presentación organizacionamente

## to-do
- [x] esquema y guión de presentación
- [x] analisis -> organización + Stack tecnologico
- [x] caso de uso -> mock up
- [ ] inicio con explicación sencilla y clara
- [ ] reducir slides y sintetizar
- [ ] end page (branding and contact)
- [ ] notas de orador sintéticas

## recursos
- slides
- doc

**Comment by JSnow11** [comment]
## Esquema de presentación
1. Inicio efectivo
2. Indice
3. Key business idea
    - elevator pitch
    - tipo de negocio
    - innovación
    - competidores
    - DAFO
    - riesgos
    - costes
4. MVP
5. plan de usuarios piloto
6. Equipo
    - estructura org
    - subequipos
    - roles, skills y responsabilidades
    - control de rendimiento
7. Metodología
    - stack tecnológico
    - ADM
    - metodología de desarrollo (workflow)
    - gestión de la calidad
8. Plan de ejecución inicial
    - Sprints
    - Sprint 1
