### ISSUE TITLE
task - Add images for sponsorship's and locations

### ISSUE THREAD

**Issue by pedalopon** [ISPP-Eventia/eventus#325]
## description 
Search and upload images related to the existing locations and sponsorship's

## to-do
- [ ] Search for images 
- [ ] Upload images and added to the existing locations and sponsorship's

## accept
- [ ] New locations and sponsorship's are showing in the front view of sponsorship's and locations
