### ISSUE TITLE
doc - análisis de coste / beneficios

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#33]
## descripcion
realizar un análisis optimista / pesimista / realista de costes y beneficios.

contabilizar numero transacciones e indicar % de cobro

> EJ: n* de transacciones (40000), es demasiado optimista, deben preeverse otras posibles situaciones.

## to-do
- [x] optimista
- [x] realista
- [x] pesimista
- [x] especificar las métricas de las que se depende
- [x] especificar métrica temporal (puntual, mensual, anual)
- [x] tipos (nomina, amortización, apoyo, indirectos)

## recursos
- slides
- doc

**Comment by carvilgar1** [comment]
Todas las métricas de costes recurrentes ahora se han convertido a €/mes y la escala temporal de las gráficas se ha convertido a €/mes

**Comment by ferrabled** [comment]
Se han reestructurado las diapositivas para intentar dar toda la información en menos slides.
También se han corregido los errores encontrados

**Comment by ferrabled** [comment]
Se han corregido las gráficas y datos de costes vs beneficios en el archivo [Excel](https://docs.google.com/spreadsheets/d/1_oIm-pzVZcl8iAASLwDa3c0umyBQpLtZ/)
