### ISSUE TITLE
task - check and fix feedback bugs and suggestions

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#334]
## related
- related to #307

## description 

Los usuarios piloto han reportado lo siguiente: 

## BUGS:
- [x] El usuario sale dos veces al participar en un torneo donde no había nadie
- [x] Al participar en un evento lleva a la pasarela de pago para añadir una tarjeta pero luego no  redirecciona al evento seleccionado sino que tengo que volver a buscarlo y participar de nuevo
- [x] Al participar en un evento compré tres tickets sin querer
- [x]  La contraseña no tiene mínimo 
- [x] Si pongo la fecha de hoy , me sale birthdate: y el error, debería no salir lo de birthdate . He puesto que nací ayer y me ha dejado, en una cosa que hay que poner dinero debería ser al menos +16 
- [x] Cuando no estás logueado te sale tu perfil y el icono de logout.
- [x] Cuando me registro en un evento , durante un tiempo me salta "ya estás registrado en este evento" pero no me he registrado todavía.

## IMPROVEMENTS:
- [x] Cambiar el símbolo del dólar por el del euro
- [x] Cambiar el botón de inicio de sesión a uno más intuitivo
- [x] Búsqueda de eventos por cercanía
- [x] Seleccionar número de tickets que quiero comprar
- [x] Regalar tickets a otro usuario registrado
- [x] El botón de 'Mostrar todos' (eventos) podría ser más vistoso

Internamente hemos reportado lo siguiente:

- cuando buscas tienes que iniciar sesión pero al principio como que funciona 
- login está en inglés pero luego todo está en castellano
- Creo que en proporción está todo muy pequeño
- El login podría estar centrado, que se pierde mucha pantalla a la derecha
- los iconos inferiores en la página principal parece con los puntos suspensivos que te van a llevar a algún lado si haces click en ellos, pero no te llevan a ningún lado Es como que intuitivamente los vas a seleccionar. 
Se podría poner alguna frase encima como: con eventus puedes: y ya que aparezcan abajo o algo. 
Cuando le das a comenzar te lleva como a inciar pero luego te pide el inicio de sesión. 
- El no tienes cuenta? Regístrate ya! Debe iniciar también con los signos de exclamación e interrogación. 
- En la dirección aparece el código postal abajo sin híper vínculo, queda raro que aparezca reina mercedes y eso no. A lo mejor en la misma línea con hipervinculo queda mejor. 
- En “organiza”. Compártelos lleva tilde.
- En “Participa” lo de compite en eventos competitivos queda rarillo 
- En “Aloja” ofreciéndola lleva tilde
- No puedes escribir la fecha a mano
- Las imágenes me salen con error, no sale la foto (puede ser porque esté en navegador de incógnito, no puedo abrirlo sin navegador privado en este pc que tengo)
-mucho espacio en blanco entre el evento y los participantes y sugerencias
-cuando quieres editar un campo del perfil hay que rellenarlos todos otra vez

## to-do
- [ ] comprobar y resolver bugs
- [ ] intentar añadir algunas de las peticiones y sugerencias

## accept
- [ ] el feedback es reflejado en la nueva versión de la app
