### ISSUE TITLE
doc - Inicio Efectivo

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#34]
## descripcion
necesitamos un inicio de presentación efectivo, debe cumplir lo siguiente:
- ser llamativo
- estar relacionado con el ámbito de la app
- ser reconocible
- incluya o referencie al publico para activarlo

## to-do
- [x] idear un inicio efectivo
- [x] elaborar un breve guión 
- [x] incluir el guión en las notas de orador de la primera diapositiva

## recursos
- enlaces de documentos o archivos
- enlaces de recursos útiles
