### ISSUE TITLE
doc - Plan de Marketing

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#346]
## descripcion
descripción detallada de lo que debe ser documentado, como y donde.

## to-do
- [x] Modelo de Segmentación
- [x] Perfiles de viewers objetivo de los anuncios
- [ ] Generar Hype (propuestas e ideas, eslogan, promociones, sorpresas)
- [ ] tamaño de audiencia esperada
- [ ] Impresiones esperadas
- [ ] Costes (anuncios, impresiones, analisis, ...)
- [ ] Fidelización de usuarios
- [ ] Herramientas
