### ISSUE TITLE
doc - revisar elevator pitch

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#35]
## descripcion
el elevator pitch debe clarificar de forma concisa pero detallada el alcance y ámbito de la aplicación marcando de forma clara qué nos define

puede hacerse uso de la plantilla:

**Para** ... **que** quieran/buscan/necesitan ..., **EventUs** es ... que **permite** ... **para** ... . **(A diferencia/En vez) de** ..., **nuestro producto** ... .

## to-do
- [x] revisar el elevator pitch
- [x] seguir la plantilla
- [x] elaborar un elevator pitch efectivo que introduzca de forma clara la app

## recursos
- enlaces de documentos o archivos
- enlaces de recursos útiles

**Comment by JSnow11** [comment]
## review
> Para empresas o particulares que buscan interaccionar con eventos o actividades, EventUs es una progressive web application (PWA) que unifica la gestión, organización, participación, promoción y alojamiento de eventos. 
A diferencia de nuestros competidores, nuestro producto unifica el mundo de los eventos acercando a todos los posibles interesados.

- me falla la palabra "interaccionar" creo que no representa bien, es demasiado genérica

**Comment by JSnow11** [comment]
> ## review
> > Para empresas o particulares que buscan interaccionar con eventos o actividades, EventUs es una progressive web application (PWA) que unifica la gestión, organización, participación, promoción y alojamiento de eventos.
> > A diferencia de nuestros competidores, nuestro producto unifica el mundo de los eventos acercando a todos los posibles interesados.
> 
> * me falla la palabra "interaccionar" creo que no representa bien, es demasiado genérica

cambiado por _interactuar_
