### ISSUE TITLE
doc - plan de gestión de calidad y mejora

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#43]
## descripcion
definir el plan de calidad y mejora del proyecto

## to-do
- [x] métricas de calidad
- [x] metodos de medición
- [x] metodos de análisis

## recursos
- [plan de gestión de calidad](https://docs.google.com/document/d/1XbMST-UmiY_F050-bOLkGqhlRLot_LiW1praAVbP1cQ/edit?usp=sharing)

**Comment by pedalopon** [comment]
Se ha creado un documento Plan de Gestión de Calidad / Control del Rendimiento donde se detalla el plan de gestión de la calidad a seguir en el proyecto. En la diapositiva correspondiente a este punto se habla de las métricas y el significado de cada una y el plan de gestión de la calidad a seguir en el proyecto de manera resumida mediante un pequeño esquema.
