### ISSUE TITLE
doc - ALM

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#45]
## descripcion
tecnologías de gestión, desarrollo, despliegue ...

## to-do
- [x] plan (github + projects)
- [x] ci/cd (actions)
- [x] análisis de calidad de código (codacy?)
- [x] timetracking (clocki)
- [x] versionado (semántico)
- [x] despliegue 

## recursos
- enlaces de documentos o archivos
- enlaces de recursos útiles
