### ISSUE TITLE
doc - plan de desarrollo 

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#48]
## descripcion
definir la carga de trabajo, objetivos y funcionalidades de forma general en sprints y de forma concreta para el sprint 1

## to-do
- [x] introducir epic stories 
- [x] crear milestones para los diferentes sprints
- [x] dividir y organizar las historias epicas del sprint 1
