### ISSUE TITLE
doc - entrega miercoles 02/03

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#49]
## descripcion
descripción detallada de lo que debe ser documentado, como y donde.

## to-do
- [ ] PDFs
    - [ ] nºgrupo-presentacion.pdf
    - [ ] nºgrupo-informe.pdf (contribución a base de conocimiento)
    - [ ] nºgrupo-piloto.pdf (se puede incluir encuestas)
    - [ ] adicionales

## recursos
- enlaces de documentos o archivos
- enlaces de recursos útiles

**Comment by JSnow11** [comment]
## review
- Acuerdo de equipo
    - compromiso, muy detallado en el sentido del compromiso de actitud pero no se especifica el compromiso de responsabilidades y roles
    - plan de pruebas: no parece encajar en el contexto del documento, el contenido no esta relacionado con las pruebas, el workflow podria citarse y enlazarse al readme de github, pero no veo necesario detallarlo aquí

**Comment by JSnow11** [comment]
## review
- informe de aportación 
    -  falta una introducción indicando como organizamos la gestión del conocimiento y explicando la metodología de recolección de feedback y de unificación de forma interna (nuestro grupo) y externa (con otros grupos)

@antsandur2

**Comment by antsandur2** [comment]
Se ha colocado una introducción indicando la metodología de recolección de Feedback, como lo unificamos de forma interna y la aportación a la base compartida.
 

    En miércoles, 9 de marzo de 2022, 19:35:47 CET, José Nieves ***@***.***> escribió:  
 
 


review
   
   - informe de aportación      
      - falta una introducción indicando como organizamos la gestión del conocimiento y explicando la metodología de recolección de feedback y de unificación de forma interna (nuestro grupo) y externa (con otros grupos)


@antsandur2

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by antsandur2** [comment]
La responsabilidad y roles está explicada en el apartado de responsabilidad de forma escueta. El plan de prueba lo he eliminado del documento y cuando se hace referencia al Workflow he colocado un enlace al documento readme.
 

    En miércoles, 9 de marzo de 2022, 19:33:03 CET, José Nieves ***@***.***> escribió:  
 
 


review
   
   - Acuerdo de equipo      
      - compromiso, muy detallado en el sentido del compromiso de actitud pero no se especifica el compromiso de responsabilidades y roles
      - plan de pruebas: no parece encajar en el contexto del documento, el contenido no esta relacionado con las pruebas, el workflow podria citarse y enlazarse al readme de github, pero no veo necesario detallarlo aquí


@antsandur2

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
