### ISSUE TITLE
task - landing page

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#52]
## related
- blocked by #46 

## description 
Pagina de inicio de la app, se puede usar una plantilla y debe contener:
- elevator pitch
- info de contacto

## to-do
- [ ] configurar tailwind (colores y fuentes)
- [ ] configurar mui (colores y fuentes)
- [x] react page (usando el componente base)
- [ ] asegurar que es visible

## accept
- [ ] al desplegar en local o producción podemos ver la landing page en la ruta inicial
