### ISSUE TITLE
story - participar en evento 

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#54]
## related
- blocked by #53 

## description 
**como** _participante_ 

**quiero** que se recomienden eventos, poder buscarlos, verlos en detalle y participar en ellos y recibir un ticket de participación

**para** facilitarme el proceso de participación

### design

![image](https://user-images.githubusercontent.com/47798577/155889688-384b8526-3e64-4052-8e5d-1f331931abd4.png)

[click here](https://www.figma.com/file/7ncBwZS520GKSlelXwdCkM/Eventus?node-id=7%3A2)

## to-do
- [x] #66 
- [x] #68
- [x] #69
- [x] #67 
- [x] #71
- [x] #72
- [x] #73
- [x] #65 

## accept
A clear and concise description of the acceptance conditions
- [ ] la pagina pricipal muestra los eventos recomendados o existentes
- [ ] los eventos pueden abrise y se muestra la pagina detallada de evento
- [ ] la pagina detallada permite la participación en eventos mediante un formulario (drawer) de participación
