### ISSUE TITLE
story - patrocinar evento

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#55]
## related
- blocked by #53 

## description 
**como** _patrocinador_ 

**quiero** poder realizar propuestas de patrocinio, indicando una suma de dinero y un anuncio (imagen, video ...) que será mostrado a todos los que visiten la pagina de detalle del evento si dicha propuesta es aceptada

**para** apoyar al evento y conseguir difusión y visibilidad a cambio

### design

![image](https://user-images.githubusercontent.com/47798577/155889798-08d8c373-5514-40f0-987c-edef1e75262c.png)

![image](https://user-images.githubusercontent.com/47798577/155890041-4ed872a5-9cde-4966-8995-22fe25a10a94.png)

[click here](https://www.figma.com/file/7ncBwZS520GKSlelXwdCkM/Eventus?node-id=7%3A2)

## to-do
- [x] #75 
- [x] #74 
- [x] #76

## accept
- [ ] el formulario de patrocinio permite crear solicitudes de patrocinio
- [ ] en la vista de detalles de un evento propio aparecen las solicitudes de patrocinio
- [ ] las solicitudes pueden aceptarse o rechazarse
- [ ] los anuncios de las solicitudes aceptadas aparecen en la vista de detalles
