### ISSUE TITLE
story - compartir en redes sociales 

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#58]
## description 
**como** _usuario_ 

**quiero** poder compartir de forma sencilla mis eventos, experiencias (solo si tiene participación) en ellos y mis infraestructuras de forma sencilla desde la app, teniendo posts predefinidos con cierta estructura en instagram, twitter, facebook, whatsapp, telegram ... además, sería interesante que se crearan hashtags automaticos para los eventos

**para** facilitarme la difusión de eventos, infraestructuras y experiencias en mis redes sociales

### design
TODO

## to-do
- [ ] añadir la funcionalidad de compartir
- [ ] definir la plantilla de post por defecto
- [ ] mostrar el hashtag autogenerado para cada evento
- [ ] añadir los botones o usar directamente el hashtag como botón de compartir en la app

## accept
- [ ] un usuario puede compartir sus eventos, infraestructuras o experiencias en eventos de forma sencilla
