### ISSUE TITLE
story - pagos 

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#59]
## description 
**como** _administrador_ 

**quiero** que los usuarios puedan realizar pagos de forma sencilla en mi app, tomando siempre cierta comisión de por medio

**para** facilitar las transacciones de dinero dentro de la app

### backend
- [x] #154

### frontend
- [x] #153
- [x] #155

### integration
- [x] #156

## accept
A clear and concise description of the acceptance conditions
- [ ] los usuarios pueden realizar pagos en la app
- [ ] la app gestiona las comisiones y las muestra de antemano
- [ ] todas las transacciones hacen uso del modulo de pago
