### ISSUE TITLE
story - mejorar el matchmaking 

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#60]
## related
- child of #54 

## description 
**como** _participante_ 

**quiero** que las recomendaciones ofrecidas sean inteligentes, efectivas y relevantes

**para** encontrar eventos relevantes de forma más sencilla

> se baraja el uso de un sistema de recomendación basado en contenido y otro basado en datos de uso de la app 

## to-do
- [ ] diseño arquitectonico de los sistemas de recomendacion mejorados
- [ ] sistema basado en contenido
- [ ] sistema basado en uso
- [ ] aplicar los sistemas a los eventos recomendados de la pagina principal

## accept
- [ ] los usuarios reciben eventos más relevantes
