### ISSUE TITLE
story - añadir contenido a un evento 

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#61]
## related
- child of #53 

## description 
**como** _organizador_ 

**quiero** poder subir contenido (fotos, videos ...) sobre mis eventos y que estos puedan verse de forma sencilla

**para** promocionar y dar información interna sobre mi evento

### design
TODO

## to-do
A clear and concise description of the steps or parts that would complete the feature
- [ ] uso del sistema de anuncios para subir clips/imagenes
- [ ] acceso directo desde la tarjeta de evento
- [ ] visualizar desde la pagina de detalles de evento

## accept
A clear and concise description of the acceptance conditions
- [ ] el organizador de un evento puede subir clips o imagenes sobre un evento
