### ISSUE TITLE
task - formulario de eventos

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#63]
## related
- child of #53 

## description 
Interfaz para el formulario de creación/edición de eventos

### design
TODO

## to-do
- [ ] uso de componente de pagina con estructura base
- [ ] inputs
- [ ] buttons
- [ ] funcionalidad para creación y edición

## accept
A clear and concise description of the acceptance conditions
- [ ] existe un componente "EventForm" que permite la creación/edición de eventos
