### ISSUE TITLE
task - (integración) eventos

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#64]
## related
- blocked by #62 and #63 
- child of #53 

## description 
Llamadas al backend para CRUD de eventos e integración del formulario de eventos

## to-do
- [ ] definir las funciones API calls de evento
- [ ] integrar el formulario de eventos mediante las API calls con el backend

## accept
- [ ] el formulario de eventos es completamente funcional y esta integrado con el backend
