### ISSUE TITLE
task - endpoint participación

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#65]
## related
- child of #54 

## description 
Implementación de usuario y de su relación con evento facilitando operaciones de participación (relacion), ofreciendo un servicio para poder crear relaciones entre el usuario logeado y el evento dado

## to-do
- [x] #97 
- [x] participar en evento
- [x] facilitar la futura integración del modulo de pago
- [ ] Test endpoint participación

## accept
- [x] existe un servicio para que el usuario logueado participe en un evento
- [ ] documentación sobre el servicio
### Postman collection
[https://drive.google.com/file/d/1Sn5dR75U2I63kfP6h7J-CPYNLfR94hTT/view?usp=sharing](url)
### createParticipation 
POST /participations
#### JSON body example 
{
  "eventId": 1
}
### getParticipations
GET /participations
#### URL PARAMS
- numPag: Pagintation number
### getParticipationById
GET /participations/{id}
#### PATH PARAMS
- id: participation id to get
### getUsersByEvent
GET /user/event/{eventId}
#### PATH PARAMS
- eventId: event id to list user participations
### getParticipationsByUser
GET /participations/user/{userId}
#### PATH PARAMS
- userId: userId to get user participations
### getParticipationsByEvent
GET /participations/event/{eventId}
#### PATH PARAMS
- eventId: event id to list participations
### deleteParticipation
DELETE /participations/{id}
#### PATH PARAMS
- id: participation id to delete
