### ISSUE TITLE
task - lista de eventos

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#66]
## related
- child of #53 #54 #55 

## description 
Componente de lista de eventos

### design
![image](https://user-images.githubusercontent.com/47798577/155997111-a21ad68f-83d8-43b4-8443-63a8606a695b.png)

![image](https://user-images.githubusercontent.com/47798577/155997157-66501dd3-d6c6-4cbf-bec0-86c00ecdc028.png)

## to-do
- [x] hacer uso del componente base de pagina
- [x] implementar el componente de lista de eventos
- [x] Implementar tarjeta de evento
- [x] hacer uso de dummies para validar su funcionamiento

## accept
- [x] existe un componente de lista de eventos
