### ISSUE TITLE
task - event detail page

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#67]
## related
- child of #53 #54 #55 

## description 
Componente de detalles de eventos

### design
![image](https://user-images.githubusercontent.com/47798577/155998733-e2c33db3-f920-4a17-aef6-1f7d4c107cff.png)

![image](https://user-images.githubusercontent.com/47798577/155998791-9eff6b8e-1f8d-4a86-854d-029ae45073af.png)

## to-do
- [ ] hacer uso del componente base de pagina
- [ ] implementar el componente de detalle de evento
- [ ] diferenciación de funcionalidad en función del usuario que visita la página (dueño o no)

## accept
- [ ] existe un componente de lista de eventos
