### ISSUE TITLE
task - results page

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#69]
## related
- child of #54 

## description 
componente para la pagina de resultados

### context
se puede reutilizar el componente lista de eventos (#66) cambiando el título e indicando los resultados

### design
![image](https://user-images.githubusercontent.com/47798577/156024392-1cfe75f5-cd7b-41c6-a791-841524dcc4d1.png)

## to-do
- [ ] reusar el componente lista de eventos
- [ ] añadir la funcionalidad de results page

## accept
- [ ] el componente de lista de eventos puede usarse como results page
