### ISSUE TITLE
task - drawer de participación

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#71]
## related
- child of #54 

## description 
formulario de participación en forma de drawer / modal

> el formulario debe ser facilmente ampliable puesto que se tendrá que añadir la pasarela de pago

### design
![image](https://user-images.githubusercontent.com/47798577/156025364-dca650b4-a0b1-437f-ab25-2551a339cc12.png)

## to-do
- [ ] uso del componente drawer
- [ ] formulario de participación

## accept
- [ ] existe un componente "ParticipateForm" con la lógica de creación de participaciones
