### ISSUE TITLE
task - ticket downloader

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#72]
## related
- child of #54 

## description 
modal o drawer indicando la generación de ticket y un botón para descargarlo

> puede integrarse dentro del formulario de participación puesto que esta directamente relacionado y forma parte del proceso de participación

### design
Links to the designed results

## to-do
- [ ] uso del componente modal o drawer (por decidir)
- [ ] integración dentro del formulario de participación

## accept
- [ ] el componente de formulario de participación permite descargar el pdf generado al final del proceso de participación
