### ISSUE TITLE
task - generación de ticket

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#73]
## related
- child of #54 

## description 
generación y descarga de pdfs con el ticket de participación al completar el proceso de creación de participación

## to-do
- [ ] tomar #65 como base
- [ ] gestión y creación de tickets
- [ ] creación de pdfs
- [ ] añadir el proceso de ticket al servicio de creación de participación
- [ ] Test endpoint  ticket

## accept
- [ ] el endpoint de participación incluye la generación de tickets
