### ISSUE TITLE
task - endpoint patrocinio

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#75]
## related
- child of #55 

## description 
endpoint que incluya la gestión de anuncios, ofertas de patrocinio y la relación entre sponsor y evento (sponsorship)

## to-do
- [ ] crear oferta de patrocinio (anuncio, suma de dinero, estado aceptada/rechazada ..)
- [ ] relación intermedia entre sponsor y evento (oferta de patrocinio)
- [ ] consulta de ofertas para un evento y para un usuario (eventos de ese usuario)
- [ ] acción de aceptación/rechazo de oferta (U)

## accept
- [ ] endpoint para la gestión de patrocinios usable y documentado
