### ISSUE TITLE
task - componente anuncio

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#76]
## related
- child of #55 

## description 
componente anuncio para mostrar anuncios dentro de la #67 

## to-do
- [ ] componente de anuncio
- [ ] incluir anuncios en la edp #67 

## accept
- [ ] el componente de anuncio es usable con imagenes o videos
