### ISSUE TITLE
task - endpoint alojamiento

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#79]
## related
- child of #56 

## description 
Implementación de infraestructura como entidad, y su relación con usuario y evento, facilitando operaciones CRUD de infraestructura, creación de solicitudes de alojamientos (relación), función de aceptación/rechazo ... 

## to-do
- [x] #100
- [x] #101
- [x] CRUD infraestructura
- [x] crear solicitud de alojamiento (evento - infraestructura)
- [x] aceptar/rechazar solicitud
- [ ] Test endpoint alojamiento

## accept
- [x] existe un servicio para que el usuario pueda publicar infraestructuras
- [x] existe la posibilidad de presentar solicitudes de alojamiento entre evento e infraestructura
- [x] la disponibilidad de la infraestructura es actualizada automáticamente
