### ISSUE TITLE
task - formulario infraestructura

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#80]
## related
- child of #56 

## description 
Interfaz para el formulario de creación/edición de infraestructuras

### design
TODO

## to-do
- [x] uso de componente de pagina con estructura base
- [x] inputs
- [ ] buttons
- [ ] funcionalidad para creación y edición

## accept
- [ ] existe un componente "InfraestructureForm" que permite la creación/edición de infraestructuras (alojamientos)
