### ISSUE TITLE
task - infraestructure detail page

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#81]
## related
- child of #56 

## description 
Componente para la pagina de detalle de infraestructura

### design
![image](https://user-images.githubusercontent.com/47798577/156047755-de08754f-20c6-43eb-874c-186a801ded47.png)
![image](https://user-images.githubusercontent.com/47798577/156047693-1f4df0d1-054c-4a14-87a4-d6d1bd71c47d.png)

## to-do
- [ ] hacer uso del componente base de pagina
- [ ] implementar el componente de detalle de infraestructura
- [ ] diferenciación de funcionalidad en función del usuario que visita la página (dueño o no)

## accept
- [ ] existe un componente para la pagina en detalle de infraestructura
