### ISSUE TITLE
task - drawer de solicitud de alojamiento

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#82]
## related
- child of #56 

## description 
formulario de solicitud de alojamiento en forma de drawer / modal

> el formulario debe ser facilmente ampliable puesto que se tendrá que añadir la pasarela de pago

### design
![image](https://user-images.githubusercontent.com/47798577/156048122-8ab6aadd-f3fb-4763-bf6a-f0d74c86fc17.png)

## to-do
- [ ] uso del componente drawer
- [ ] formulario de solicitud de alojamiento

## accept
- [ ] existe un componente "HostRequestForm" con la lógica de creación de solicitudes de alojamiento
