### ISSUE TITLE
task - infraestructure list

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#83]
## related
- child of #53 #54 #55 
- similar to #66 

## description 
Componente de búsqueda y lista de infraestructuras

### design
![image](https://user-images.githubusercontent.com/47798577/156048811-6643dea2-7029-4bce-a80d-2c767bc6718b.png)

## to-do
- [ ] hacer uso del componente base de pagina
- [ ] implementar el componente de lista de infraestructuras
- [ ] hacer uso del componente de búsqueda pero aplicado a infraestructuras

## accept
- [ ] existe un componente de lista de infraestructuras
