### ISSUE TITLE
doc - definición del formato de las nuevas slides

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#84]
## descripcion
tomar la plantilla desde 0, modificar los colores usando la funcionalidad "editar tema"

![image](https://user-images.githubusercontent.com/47798577/156623803-3d479d2f-7db1-45ea-852a-b97e1a382004.png)

## to-do
- [ ] crear nuevo archivo pptx con la plantilla original
- [ ] modificar los colores en base a la paleta de colores
    - [ ] asegurar que hay contraste aceptable entre texto y fondo 
- [x] asegurar consistencia de iconos / imagenes
- [x] fomentar el uso de las plantillas del tema
- [x] no crear / modificar las plantillas de forma concreta sino de forma general
