### ISSUE TITLE
doc - migrar diapositivas

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#85]
## related
blocked by #84 

## descripcion
una vez definido el formato, se debe migrar el contenido, cada persona sera responsable de hacerlo inicialmente, teniendo en cuenta las guías e instrucciones que se den desde el equipo de documentación

el feedback indica que el contenido es el adecuado, evitad modificarlo, centremonos en seguir el nuevo formato y reducir el nº de diapositivas cuando sea posible o necesario.

## to-do
- [ ] leer y comprender las guías de formato
- [ ] migrar el contenido a las diapositivas
- [ ] comprobar que el formato es correcto y preguntar si se tienen dudas
