### ISSUE TITLE
task - setup github actions

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#87]
## description 
Necesitamos tener un workflow inicial que, en base al setup inicial de la aplicación, construya tanto el frontend como el backend, detectando posibles errores de construcción y analice el código, mediante codacy.

El workflow debe ejecutarse en PRs dirigidas a develop o main y puede dividirse en subpartes si se considera de utilidad

> Nota: podría añadirse el proceso de despliegue si fuera posible temporalmente

## to-do
- [x] check de los pasos de construcción del backend y frontend
- [x] configurar codacy
- [x] crear un workflow inicial que compruebe la construcción y analice el código
- [x] añadir el workflow como requisito de validación de la PR (no se puede mergear si no pasan los checks)

## accept
- [ ] existe un workflow inicial para comprobar la correcta construcción de las apps y la calidad del código
