### ISSUE TITLE
doc - social media

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#88]
## descripcion
crear perfiles de redes sociales para la app

## to-do
- [x] crear perfiles para
    - [x] twitter
    - [x] instagram
    - [x] facebook
 - [ ] documentar los enlaces a los perfiles
 - [ ] documentar de forma privada interna las credenciales

**Comment by JSnow11** [comment]
## Posibles usernames

![8dd87a77-49ea-4ed8-a27f-8b1c5c8a9ceb](https://user-images.githubusercontent.com/47798577/157314306-5068308e-71e0-4a16-b3db-187ff498efa1.jpg)

**Comment by marpedrod3** [comment]
Se han creado las rr.ss
