### ISSUE TITLE
doc - feedback fixes

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#92]
## descripcion
feedback sesión de evaluación

## to-do
- [ ] reducir diapositivas
- [x] Eliminar índice si no se está leyendo (feedback de otro grupo)
- [x] d5 -> mucho texto
- [ ] d8 -> complejdad alta
- [x] Costes -> colores mas diferenciados
- [ ] añadir riesgo: poco uso o aceptacion
- [ ] DAFO: evitar covid (ciranstancial)
- [x] grupos: Nombres de los Integrates
- [x] versionado (semantico)
- [x] Añadir más información sobre las preguntas de las encuestas
- [ ] competidores: justificar, métricas, por qué mejores?
- [ ] justificar la comision decidida
