### ISSUE TITLE
doc - review guide

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#93]
## descripcion
guía de revisión de la funcionalidad implementada en el sprint

## to-do
- [x] análisis de la guia solicitada
- [x] explicar la funcionalidad implementada
- [x] pasos para revisar
- [x] credenciales

## recursos
- guia: subida en la enseñanza virtual como un pdf con los elementos que debe contener la review guide
